//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farif.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>true;.asp</string>
  <string>true;.bat</string>
  <string>true;.c</string>
  <string>true;.cmd</string>
  <string>true;.cpp</string>
  <string>true;.cs</string>
  <string>true;.css</string>
  <string>true;.h</string>
  <string>true;.hh</string>
  <string>true;.hpp</string>
  <string>true;.htm</string>
  <string>true;.html</string>
  <string>true;.ini</string>
  <string>true;.kml</string>
  <string>true;.mxml</string>
  <string>true;.pas</string>
  <string>true;.php</string>
  <string>true;.php3</string>
  <string>true;.php4</string>
  <string>true;.php5</string>
  <string>true;.phps</string>
  <string>true;.phpt</string>
  <string>true;.phtml</string>
  <string>true;.py</string>
  <string>true;.shtml</string>
  <string>true;.svg</string>
  <string>true;.txt</string>
  <string>true;.vb</string>
  <string>true;.wsdl</string>
  <string>true;.xaml</string>
  <string>true;.xhtml</string>
  <string>true;.xlf</string>
  <string>true;.xml</string>
  <string>true;.xs</string>
  <string>true;.xsd</string>
  <string>true;.xslt</string>
  <string>true;.xsml</string>
  <string>false;desktop.ini</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileFilter"]));
            }
            set {
                this["FileFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsIncludeSubFolders {
            get {
                return ((bool)(this["IsIncludeSubFolders"]));
            }
            set {
                this["IsIncludeSubFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRepairLfCr {
            get {
                return ((bool)(this["IsRepairLfCr"]));
            }
            set {
                this["IsRepairLfCr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedLineEnding {
            get {
                return ((string)(this["SelectedLineEnding"]));
            }
            set {
                this["SelectedLineEnding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedInputPath {
            get {
                return ((string)(this["SelectedInputPath"]));
            }
            set {
                this["SelectedInputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRepairLfCrEnabledState {
            get {
                return ((bool)(this["IsRepairLfCrEnabledState"]));
            }
            set {
                this["IsRepairLfCrEnabledState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTryDetectEncoding {
            get {
                return ((bool)(this["IsTryDetectEncoding"]));
            }
            set {
                this["IsTryDetectEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSearchText {
            get {
                return ((string)(this["LastSearchText"]));
            }
            set {
                this["LastSearchText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastReplaceText {
            get {
                return ((string)(this["LastReplaceText"]));
            }
            set {
                this["LastReplaceText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSearchAndReplaceCaseSensitive {
            get {
                return ((bool)(this["IsSearchAndReplaceCaseSensitive"]));
            }
            set {
                this["IsSearchAndReplaceCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSearchAndReplace {
            get {
                return ((bool)(this["IsSearchAndReplace"]));
            }
            set {
                this["IsSearchAndReplace"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OutputIntervall {
            get {
                return ((int)(this["OutputIntervall"]));
            }
        }
    }
}
